### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by seara2k** [seara2k/3BR-base#3]
- [x] Добавить интеграцию с pickle файлом
- - [x] Добавить файл класс датабазы
- - [x]  Удаление элементов 
- - [x]  Добавление элементов 
- - [x]  Изменение элементов 
- [x] Разобраться с расположением файлов
- [x] Доделать анализ
- - [x]  Базовая статистика
- - [x]  Сводная таблица
- - [x]  Столбчатая гиаграмма
- - [x]  Гистограмма
- - [x]  Бокс вискер
- - [x]  Диаграмма рассеивания
- - [x]  Экспорт отчетов
- [x] Баги
- - [x]  Добавить messagebox к ошибкам
- - - [x] При входе
- - - [x] При неправильном вводе
- - - [x] При неправильном выборе в анализе
- - [x]  Исправить баг с grab_set после закрытия base_stats_window
- - [x]  Пофиксить сортировку в базовой статистике
- - [x]  Добавить умный ввод ко ключу
- - [x] Пофиксить всякое деление на ноль в функциях lib\base_stats
- - [x] Подправить размер кнопок на главном экране
- [x] Допилить импорт и экспорт из excel
- [x] Добавить фильтрацию
- [x]  Руководство пользователя
- [x]  Док стринги
- [x]  Убрать щит(shit) из кода
